### PR TITLE
Setup discord webhook

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Uses: https://github.com/marketplace/actions/actions-status-discord

### CODE REVIEW

**Comment by wycats** [comment]
@NullVoxPopuli What do we still need for this?

**Comment by NullVoxPopuli** [comment]
an admin needs to verify that the configs / setup are correct, and then we test if the hook is configured via pushing to this branch

**Comment by wycats** [comment]
@NullVoxPopuli Should I just close this and we can come back to it later?

**Comment by NullVoxPopuli** [comment]
may as well, ya

**Pull request closed without merging**
